### ISSUE TITLE
Missing Explicit (Re-)Export

### ISSUE THREAD

**Issue by BenediktAllendorf** [kmagusiak/odoo-connect#23]
Hey there,

After upgrading to v0.4 (and thus, activating type checking for this dependency), mypy throws several errors like this:
`error: Module "odoo_connect" does not explicitly export attribute "OdooClient"  [attr-defined]`.

`from odoo_connect import OdooClient` leads to the error, `from odoo_connect.odoo_rpc import OdooClient` is fine.

From what I understand, explicitly adding those imports to `__all__` in the `__init__.py` would fix this. But, for now, we have the following workaround in our pyproject.toml:
```
[[tool.mypy.overrides]]
module = ["odoo_connect"]
implicit_reexport = true
```

**Comment by kmagusiak** [comment]
Hello,

Thank you for the contribution. I don't have the issue (maybe different version of mypy), but I've merged the change anyway. It will be available with the next version.

Best regards,
Krzysztof
